---

- name: add mssql credential type
  awx.awx.tower_credential_type:
    name: mssql
    description: Microsoft SQL server credentials
    kind: cloud
    inputs:
      fields:
        - type: string
          id: mssql_username
          label: Database User
        - secret: true
          type: string
          id: mssql_password
          label: Database Password
      required:
        - mssql_username
        - mssql_password
    injectors:
      extra_vars:
        mssql_password: '{% raw %}{{ mssql_password }}{% endraw %}'
        mssql_username: '{% raw %}{{ mssql_username }}{% endraw %}'
    state: present
    tower_host: '{{ tower_host }}'
    tower_username: '{{ tower_username }}'
    tower_password: '{{ tower_password }}'
    validate_certs: '{{ tower_verify_ssl }}'
  register: reg_credential_type_mssql
  until: reg_credential_type_mssql is success
  delay: 3
  retries: 300