---

- name: ensure mssql credential exists
  awx.awx.tower_credential:
    name: mssql
    description: Microsoft SQL server credential
    credential_type: mssql
    organization: Default
    inputs:
      mssql_username: "{{ mssql_username }}"
      mssql_password: "{{ mssql_password }}"
    state: present
    tower_host: '{{ tower_host }}'
    tower_username: '{{ tower_username }}'
    tower_password: '{{ tower_password }}'
    validate_certs: '{{ tower_verify_ssl }}'
  register: reg_mssql_credential
  until: reg_mssql_credential is success
  delay: 3
  retries: 30

- name: create aws windows machine credentials
  awx.awx.tower_credential:
    name: aws-windows-machine
    inputs:
      username: 'Administrator'
      password: "{{ ansible_ssh_password | default(ansible_password) | default(omit) }}"
    credential_type: Machine
    organization: Default
    state: present
    tower_host: '{{ tower_host }}'
    tower_username: '{{ tower_username }}'
    tower_password: '{{ tower_password }}'
    validate_certs: '{{ tower_verify_ssl }}'
  register: reg_credential_aws_windows_machine

- name: create aws credentials
  awx.awx.tower_credential:
    name: aws-demo
    inputs:
      username: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') | default(omit) }}"
      password: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') | default(omit) }}"
      security_token: "{{ lookup('env', 'AWS_SECURITY_TOKEN') | default(omit) }}"
    credential_type: Amazon Web Services
    organization: Default
    state: present
    tower_host: '{{ tower_host }}'
    tower_username: '{{ tower_username }}'
    tower_password: '{{ tower_password }}'
    validate_certs: '{{ tower_verify_ssl }}'
  register: reg_credential_aws_demo