- name: Deploy Servers
  hosts: localhost
  become: false
  gather_facts: false
  connection: local
  vars_files:
    - node-config/nodes-vmware-mssql-on-linux.yml

  roles:
  - ansible-role-vmware
  
