- name: Deploy Windows Servers
  hosts: localhost
  gather_facts: false
  connection: local
  become: false
  vars:
    ansible_port: 5986
    ansible_connection: local
  vars_files:
    - node-config/nodes-vmware.yml

  roles:
  - ansible-role-vmware
  
