- name: Deploy Windows Servers
  hosts: all
  gather_facts: False
  connection: local
  become: no
  vars:
    ansible_port: 5986
    config_file: "{{ lookup('env', 'OS_CLIENT_CONFIG_FILE') }}"
  vars_files:
    - node-config/nodes-openstack.yml

  roles:
  - ansible-role-openstack