- name: Remove Windows Servers
  hosts: all
  gather_facts: false
  become: false
  connection: local
  vars:
    ansible_ssh_password: ''
  become: no
  vars_files:
    - node-config/nodes-vmware-mssql-on-linux.yml

  roles:
    - role: ansible-role-vmware
      role_action: deprovision
      delegate_to: localhost