- name: Remove music store app
  hosts: '*iis'
  gather_facts: no
  become: no
  roles:
    - role: ec2_elb_remove
      ignore_errors: yes

- name: Remove Windows instances
  hosts: localhost
  become: no
  gather_facts: no
  tasks:
    - name: get ec2 instance information
      ec2_instance_info:
        region: "{{ ec2_region }}"
        filters:
          vpc-id: "{{ ec2_vpc_id }}"
          "tag:app": music_store_demo
      register: ec2_instances

    - name: terminate instances
      ec2:
        region: "{{ ec2_region }}"
        state: "absent"
        instance_ids: "{{ ec2_instances.instances | map(attribute='instance_id') | list }}"