- name: Deploy Windows Servers on ec2
  hosts: all
  gather_facts: False
  connection: local
  become: no
  vars:
    ansible_port: 5986
    ansible_connection: local
  vars_files:
    - node-config/nodes-ec2.yml

  roles:
  - ec2-find-amis
  - ansible-role-ec2