- name: install sql server
  hosts: '*sql_server'
  pre_tasks:
    - name: set sql server ip
      add_host:
        name: sql_server
        ip_address:  "{{ ansible_private_ip | default(private_ip) | default(ansible_ip_addresses[0]) | default(ansible_host) | default(ansible_ssh_host) }}"

    - debug:
        var: hostvars['sql_server']['ip_address']
  roles:
    - sql2016

- name: install music store app
  hosts: '*iis'
  pre_tasks:
    - name: set ip address of sql server
      set_fact:
        sql_server_ip_address: "{{ hostvars['sql_server']['ip_address'] }}"
      when:
        - hostvars['sql_server']['ip_address'] is defined
  roles:
    - music-store-iis