---

- name: get sql server details
  hosts: '*sql_server'
  pre_tasks:
    - name: set sql server ip
      add_host:
        name: sql_server
        ip_address:  "{{ ansible_private_ip | default(ansible_ip_addresses[0]) | default(ansible_host) | default(ansible_ssh_host) }}"

    - debug:
        var: hostvars['sql_server']['ip_address']

- name: rolling update
  hosts: '*iis'
  serial: "50%"

  pre_tasks:

    - name: set ip address of sql server
      set_fact:
        sql_server_ip_address: "{{ hostvars['sql_server']['ip_address'] }}"
      when:
        - hostvars['sql_server']['ip_address'] is defined

    - name: de-register instance from load balancer
      local_action:
        module: ec2_elb
        region: "{{ ec2_region }}"
        ec2_elbs: "{{ ec2_name_prefix }}-{{ subdomain }}-elb-lb"
        instance_id: "{{ ec2_id }}"
        state: absent
      become: no
      vars:
        ansible_port: 22
        ansible_connection: local

  roles:
    - music-store-iis

  post_tasks:

    - name: register instance with load balancer
      local_action:
        module: ec2_elb
        region: "{{ ec2_region }}"
        ec2_elbs: "{{ ec2_name_prefix }}-{{ subdomain }}-elb-lb"
        instance_id: "{{ ec2_id }}"
        state: present
      become: no
      vars:
        ansible_port: 22
        ansible_connection: local

