---

- name: find ami id for rhel 7
  amazon.aws.ec2_ami_info:
    owners: 309956199498
    filters:
      name: "{{ ec2_image_names['rhel7'] }}"
    region: "{{ ec2_region }}"
  register: rhel7_ami_find

- name: find ami id for rhel 8
  amazon.aws.ec2_ami_info:
    owners: 309956199498
    filters:
      name: "{{ ec2_image_names['rhel8'] }}"
    region: "{{ ec2_region }}"
  register: rhel8_ami_find

- name: find ami id for rhel 9
  amazon.aws.ec2_ami_info:
    owners: 309956199498
    filters:
      name: "{{ ec2_image_names['rhel9'] }}"
    region: "{{ ec2_region }}"
  register: rhel9_ami_find

- name: find ami id for centos 8
  amazon.aws.ec2_ami_info:
    owners: 125523088429
    filters:
      name: "{{ ec2_image_names['centos8'] }}"
    region: "{{ ec2_region }}"
  register: centos8_ami_find

- name: find ami for windows 2016
  amazon.aws.ec2_ami_info:
    filters:
      name: "{{ ec2_image_names['win2016'] }}"
    region: "{{ ec2_region }}"
  register: win2016_ami_find

- name: find ami for windows 2019
  amazon.aws.ec2_ami_info:
    filters:
      name: "{{ ec2_image_names['win2019'] }}"
    region: "{{ ec2_region }}"
  register: win2019_ami_find

- name: find ami for windows 2022
  amazon.aws.ec2_ami_info:
    filters:
      name: "{{ ec2_image_names['win2022'] }}"
    region: "{{ ec2_region }}"
  register: win2022_ami_find

- name: set ami ids
  set_fact:
    ec2_ami_ids:
      rhel7: "{{ rhel7_ami_find.images[-1].image_id | default('') }}"
      rhel8: "{{ rhel8_ami_find.images[-1].image_id | default('') }}"
      rhel9: "{{ rhel9_ami_find.images[-1].image_id | default('') }}"
      centos8: "{{ centos8_ami_find.images[-1].image_id | default('') }}"
      win2016: "{{ win2016_ami_find.images[-1].image_id }}"
      win2019: "{{ win2019_ami_find.images[-1].image_id }}"
      win2022: "{{ win2022_ami_find.images[-1].image_id }}"

- debug:
    var: ec2_ami_ids
  when: ec2_ami_ids is defined

